### ISSUE TITLE
Prática 01 - Checklist

### ISSUE THREAD

**Issue by Larissamrs** [Larissamrs/GCMS-Larissa-Silva#2]
@ramidedantas 

- [ ] o Instalar Git localmente
- [ ] o Criar projeto local
- [ ] o Criar repositório local e realizar commits
- [ ] o Subir alterações para o repositório remoto
- [ ] o Fazer alterações no repositório da turma
